# Site settings
title: CocoaHeads Belgium
email-1: steven@bluecrowbar.com
email-2: jelle@codingmammoth.com
description: > # this means to ignore newlines until "baseurl:"
  Home of the Belgian CocoaHeads Chapter
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cocoaheadsbe.github.io" # the base hostname & protocol for your site
twitter_username: cocoaheadsbe
github_username: cocoaheadsbe
paginate: 10

# Build settings
markdown: kramdown
